name: projektB
version: '1.0-SNAPSHOT'
main: org.conterBlox.projektB.ProjektB
api-version: '1.21'

commands:
  bullet1:
    description: Custom bullet effect.
    usage: /bullet1
  LightBolt:
    description: Custom bullet effect.
    usage: /lightbolt